zookeeper:
  image: wurstmeister/zookeeper
  ports: 
    - "32774:2181"
kafka:
  build: .
  ports:
    - "9092"
  links: 
    - zookeeper:zk
  environment:
    KAFKA_ADVERTISED_HOST_NAME: 153.120.25.59
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
